propeller:
  aid: "3868690"
  tid: "148284"
  postback_url: 'http://ad.propellerads.com/conversion.php'

propellerAds:
  aid: "3868690"
  tid: "148284"
  postback_url: 'http://ad.propellerads.com/conversion.php?aid=3868690&pid=&tid=148284&visitor_id=${SUBID}&payout=${PAYOUT}

galaksion:
  cid: "46704"
  postback_url: 'http://postback.report/postback'

popcash:
  aid: "494702"
  type: "1"
  postback_url: 'https://ct.popcash.net/click'

clickadila:
  postback_url: 'https://tracking.clickadilla.com/in/postbacks'
  token: "m96gRV"

  

products:
  - id: 1
    name: "MMRS Accestrade"
    url: "https://atid.me/00oq0w0027gt?sub_id={subid}&type_ads={type_ads}"
    percentage: 1.0
    image: ""
  - id: 2
    name: "Shopee 10.10"
    url: "https://atid.me/go/wJUrEpFh?utm_source={spot_id}--{domain}--{type_ads}"
    percentage: 20.0
    image: "https://accesstrade.co.id/promo_campaign/1759893046_300x250.jpg"
  - id: 3
    name: "Tiktok"
    url: "https://atid.me/go/3pUnJQxp?sub_id={subid}&type_ads={type_ads}"
    percentage: 10.0
    image: "https://p16-oec-sg.ibyteimg.com/tos-alisg-i-aphluv4xwc-sg/6b376a299ea048fea209a13f9933b6eb~tplv-aphluv4xwc-resize-jpeg:800:800.jpeg?dr=15584&t=555f072d&ps=933b5bde&shp=2408c917&shcp=78ae5c14&idc=my&from=604555543"
  - id: 4
    name: "Lazada"
    url: "https://atid.me/0082ly0027gt?utm_source={spot_id}--{domain}--{type_ads}"
    percentage: 1.0
    image: "https://images.accesstrade.co.id/7ecd070e606afbf07a07c32e7267051f/862633_864x1080_20240702051401301.jpeg"
  - id: 6
    name: "Lazada Direct"
    url: "https://c.lazada.co.id/t/c.1AtghD?sub_id1={siteid}&sub_id2={sub_id}&sub_id3={type_ads}&sub_aff_id={sub_id}"
    percentage: 10.0
    image: "https://img.lazcdn.com/g/tps/images/ims-web/TB1Hs8GaMFY.1VjSZFnXXcFHXXa.png"
  - id: 7
    name: "Lazada Indra - Produk"
    url: "https://c.lazada.co.id/t/c.c2z1O9?sub_aff_id=indra"
    percentage: 10.0
    image: "https://img.lazcdn.com/g/tps/images/ims-web/TB1Hs8GaMFY.1VjSZFnXXcFHXXa.png"
  - id: 8
    name: "Lazada Indra - Campaign"
    url: "https://c.lazada.co.id/t/c.c2z1OZ?sub_aff_id=indra"
    percentage: 10.0
    image: "https://sg-test-11.slatic.net/other/lzd-ad/991485dcba5730f8d088e54e292093ef.jpeg"
  - id: 9
    name: "Shopee Direct"
    url: "https://s.shopee.co.id/9fBwjP8EwC?sub_id={campaign_id}-{spot_id}-{type_ads}-{domain}"
    percentage: 40.0
    image: ""
  - id: 10
    name: "Zataru Accestrade"
    url: "https://atid.me/0004940027gt?sub_id={subid}&type_ads={type_ads}"
    percentage: 5.0
    image: ""
  - id: 11
    name: "Gramedia Accestrade"
    url: "https://atid.me/000eul0027gt?sub_id={subid}&type_ads={type_ads}"
    percentage: 5.0
    image: ""
  - id: 12
    name: "Periplus Accestrade"
    url: "https://atid.me/000aw50027gt?sub_id={subid}&type_ads={type_ads}"
    percentage: 3.0
    image: ""