propeller:
  aid: "YOUR_AID"
  tid: "YOUR_TID"
  postback_url: 'http://ad.propellerads.com/conversion.php'

galaksion:
  cid: "46704"
  postback_url: 'http://postback.report/postback'

popcash:
  aid: "494702"
  type: "1"
  postback_url: 'https://ct.popcash.net/click'

products:
  - id: 1
    name: "SHOPEE"
    url: "https://atid.me/002d1g0027gt"
    percentage: 50.0
    image: "https://accesstrade.co.id/promo_campaign/1756699436_728x90.jpg"
  - id: 2
    name: "Blibli"
    url: "https://atid.me/00dh9j0027gt"
    percentage: 5.0
    image: "https://images.accesstrade.co.id/fb1378d0b80ae44aae0000a3cff0b90f/765927_1200x200_20240227044617887.jpg"
  - id: 3
    name: "DSC"
    url: "https://atid.me/005ff60027gt"
    percentage: 10.0
    image: "https://s3-ap-southeast-1.amazonaws.com/images.accesstrade.co.id/a8ef1979aeec2737ae3830ec543ed0df/257332_200x200_20211006064721596.jpg"
  - id: 4
    name: "Lazada"
    url: "https://atid.me/0082ly0027gt"
    percentage: 20.0
    image: "https://images.accesstrade.co.id/7ecd070e606afbf07a07c32e7267051f/862633_864x1080_20240702051401301.jpeg"
  - id: 5
    name: "EIGER"
    url: "https://atid.me/004vll0027gt"
    percentage: 4.0
    image: "https://images.accesstrade.co.id/9565f1cd832c9675c76672081c819342/839552_1192x460_20240604064621592.jpg"
  - id: 6
    name: "Lazada Direct"
    url: "https://c.lazada.co.id/t/c.1AtghD"
    percentage: 20.0
    image: "https://img.lazcdn.com/g/tps/images/ims-web/TB1Hs8GaMFY.1VjSZFnXXcFHXXa.png"
  - id: 7
    name: "Lazada Indra - Produk"
    url: "https://c.lazada.co.id/t/c.1At2Oc"
    percentage: 10.0
    image: "https://img.lazcdn.com/g/tps/images/ims-web/TB1Hs8GaMFY.1VjSZFnXXcFHXXa.png"
  - id: 8
    name: "Lazada Indra - Campaign"
    url: "https://c.lazada.co.id/t/c.1AtgSh"
    percentage: 10.0
    image: "https://img.lazcdn.com/g/tps/images/ims-web/TB1Hs8GaMFY.1VjSZFnXXcFHXXa.png"
  - id: 9
    name: "Gramedia"
    url: "https://atid.me/000eul0027gt"
    percentage: 1.0
    image: ""
