propellerAds:
  aid: "YOUR_AID"
  tid: "YOUR_TID"
  postback_url: "http://ad.propellerads.com/conversion.php"

products:
  - name: "EIGER CPS"
    url: "https://atid.me/004v1L0021t5"
    percentage: 10
  - name: "Blibli CPS"
    url: "https://atid.me/00dh9j0021t5"
    percentage: 10
  - name: "AXA Mandiri MPPT (Mandiri Proteksi Penyakit Tropis) - CPS"
    url: "https://atid.me/001ih50021t5"
    percentage: 10
