propeller:
  aid: "YOUR_AID"
  tid: "YOUR_TID"
  postback_url: 'http://ad.propellerads.com/conversion.php'

galaksion:
  cid: "46704"
  postback_url: 'http://postback.report/postback'

popcash:
  aid: "494669"
  type: "1"
  postback_url: 'https://ct.popcash.net/click'

products:
  - id: 1
    name: "EIGER"
    url: "https://atid.me/go/DOEFt9xt"
    percentage: 6
    image: "https://www.eigeradventure.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo_white.a06ea6bc.webp&w=96&q=100"
  - id: 2
    name: "Blibli"
    url: "https://atid.me/go/3uRpXt00"
    percentage: 4.8
    image: "https://www.static-src.com/siva/asset/09_2025/Lb_Tgl4_September_2025_Desktop.gif"
  - id: 3
    name: "AXA Mandiri"
    url: "https://atid.me/go/MmadBUbc"
    percentage: 10
    image: "https://axa-mandiri.co.id/image/layout_set_logo?img_id=39010002&t=1756926284720"
  - id: 4
    name: "Lazada"
    url: "https://atid.me/go/WTvq2l3w"
    percentage: 70
    image: "https://img.lazcdn.com/g/tps/images/ims-web/TB1Hs8GaMFY.1VjSZFnXXcFHXXa.png"
  - id: 5
    name: "Tiket"
    url: "https://atid.me/go/1XudxBJp"
    percentage: 3.5
    image: "https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/original/test-discovery/2024/03/01/8ebd3ae4-f545-4809-ac73-ed0fd7434377-1709290197649-a6b320e89d9f213b43896d34a3725b18.png"
  - id: 6
    name: "Samsung"
    url: "https://atid.me/go/Ee0Sd2Ln"
    percentage: 3
    image: "https://s-light.tiket.photos/t/01E25EBZS3W0FY9GTG6C42E1SE/original/test-discovery/2024/03/01/8ebd3ae4-f545-4809-ac73-ed0fd7434377-1709290197649-a6b320e89d9f213b43896d34a3725b18.png"
