products:
  # --- Shopee Direct / High Priority ---
  - name: "Shopee Direct - Anwar"
    url: "https://s.shopee.co.id/5VLlFD7dZe"
    percentage: 30

  - name: "Shopee Direct - Rima"
    url: "https://s.shopee.co.id/40X6O25UZO"
    percentage: 30

  - name: "Shopee ID KOL Tier 1 - Accesstrade"
    url: "https://atid.me/0095ot002lt5"
    percentage: 30

  # --- Lazada / Minor tracking/test ---
  - name: "Lazada Direct - Product Recommendation"
    url: "https://c.lazada.co.id/t/c.1AtgLz?sub_id1={siteid}&sub_id2={sub_id}&sub_id3={type_ads}&sub_aff_id={sub_id}"
    percentage: 2

  - name: "Lazada Direct - 9.9"
    url: "https://c.lazada.co.id/t/c.1AtgpL?sub_id1={siteid}&sub_id2={sub_id}&sub_id3={type_ads}&sub_aff_id={sub_id}"
    percentage: 2

  - name: "Lazada Kol - Accesstrade"
    url: "https://atid.me/0082ly002lt5"
    percentage: 1

  - name: "Ecomobi - Tiktok Produk B"
    url: "PASTE_LINK_BARU_DISINI"
    percentage: 3

  - name: "Involve - Traveloka"
    url: "https://invl.me/clmyea0"
    percentage: 2
